version: '3'

services:
  web:
    container_name: iShrimp_web
    restart: always
    build: .
    ports:
      - '9876:8000'
    expose:
      - 8000
    env_file: production.env
    volumes:
      - media_data:/usr/src/app/media_data
    command: sh '/usr/src/app/run_web.sh'

volumes:
  media_data:
