# Generated by Django 5.0 on 2023-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_capacity', models.FloatField()),
                ('bot_dimensions', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TripInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('banner', models.ImageField(upload_to='trip_banners/')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
