# Generated by Django 3.2.18 on 2023-12-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_tripinformation_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrosionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='corrosion_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CrackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crack_images/')),
            ],
        ),
        migrations.CreateModel(
            name='FishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fish_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pipe_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PlantsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plants_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='tripinformation',
            name='banner',
            field=models.ImageField(upload_to='trip_banners/20231219224559162'),
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(related_name='plants_objects', to='base_app.PlantsImage')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='base_app.tripinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(related_name='pipe_objects', to='base_app.PipeImage')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipe', to='base_app.tripinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(related_name='fish_objects', to='base_app.FishImage')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fish', to='base_app.tripinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Crack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(related_name='crack_objects', to='base_app.CrackImage')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crack', to='base_app.tripinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Corrosion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(related_name='corrosion_objects', to='base_app.CorrosionImage')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corrosion', to='base_app.tripinformation')),
            ],
        ),
    ]
