# Generated by Django 5.0 on 2023-12-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20231219_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrosion',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='tripinformation',
            name='banner',
            field=models.ImageField(upload_to='trip_banners/20231220000547268'),
        ),
    ]
