# Generated by Django 5.0 on 2023-12-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_rename_images_corrosion_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrosion',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='tripinformation',
            name='banner',
            field=models.ImageField(upload_to='trip_banners/20231221004700750'),
        ),
    ]
