# Generated by Django 5.0 on 2023-12-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_rename_image_corrosion_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinformation',
            name='banner',
            field=models.ImageField(upload_to='trip_banners/20231221004915681'),
        ),
    ]
