# Generated by Django 4.2.8 on 2023-12-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_alter_tripinformation_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinformation',
            name='banner',
            field=models.ImageField(upload_to='trip_banners/'),
        ),
        migrations.AlterField(
            model_name='tripinformation',
            name='end_date_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tripinformation',
            name='start_date_time',
            field=models.DateField(),
        ),
    ]
