# Generated by Django 5.0 on 2023-12-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_video_alter_tripinformation_banner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
