# Generated by Django 5.0 on 2023-12-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_alter_tripinformation_banner_and_more'),
        ('base_app', '0010_video'),
    ]

    operations = [
    ]
