# Generated by Django 5.0 on 2023-12-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_merge_20231221_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinformation',
            name='end_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tripinformation',
            name='start_date_time',
            field=models.DateTimeField(),
        ),
    ]
